//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    public partial class BookingInfo
    {
        
        public int Id { get; set; }     
        public string CustomerName { get; set; }       
        public string CustomerCardNo { get; set; }    
        public string PhoneNumber { get; set; }
         
        public string CustomerInfoOther { get; set; }
          
        public Nullable<System.DateTime> BookingDate { get; set; }
       
      
        public Nullable<System.DateTime> CheckingDate { get; set; }

      
        public Nullable<System.DateTime> CheckOutDate { get; set; }
      
        public int RoomId { get; set; }
        public bool HasChangeRoom { get; set; }
        public int FromBookingInfoId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public short StatusId { get; set; }
        public bool Deleted { get; set; }
    }
}
